Improve `define_guard` typing (#205)
* Add ParamSpec to `define_guard`

The intention is to eventually silence a couple warnings in mypy 1.19
about missing `self` arguments in the methods annotated by
`define_guard`, but this iteration does not work.

Instead, it exposed another error in `ViewStream` that is addressed in a
later commit.

    error: Self argument missing for a non-static method (or an invalid type for self)  [misc]

* Remove unnecessary type-ignore comments

* ViewStream should implement/inherit a protocol

It is not possible to satisfy the type signature of
`TextIOBase.readline` due to the conflict with `IOBase.readline`
returning a different type while still being an inherited class.
Instead, we claim that `ViewStream` implements the protocol (which is
semantically equivalent).

* Define guards as static functions

Addresses the mypy 1.19 errors that complain about the first argument of
the wrapped guard function not being `self`.

    Self argument missing for a non-static method (or an invalid type for self)

Arguably this also makes the classes easier to read.